function J = ekf_3d_jacobian_ypr_to_quat(u)

u_x = u(1);
u_y = u(2);
u_z = u(3);
u_yaw = u(4);
u_pitch = u(5);
u_roll = u(6);

J = ...
    [ 1, 0, 0,                                                                                               0,                                                                                               0,                                                                                               0;...
      0, 1, 0,                                                                                               0,                                                                                               0,                                                                                               0;...
      0, 0, 1,                                                                                               0,                                                                                               0,                                                                                               0;...
      0, 0, 0,   (cos(u_yaw/2)*sin(u_pitch/2)*sin(u_roll/2))/2 - (cos(u_pitch/2)*cos(u_roll/2)*sin(u_yaw/2))/2,   (cos(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2 - (cos(u_roll/2)*cos(u_yaw/2)*sin(u_pitch/2))/2,   (cos(u_roll/2)*sin(u_pitch/2)*sin(u_yaw/2))/2 - (cos(u_pitch/2)*cos(u_yaw/2)*sin(u_roll/2))/2;...
      0, 0, 0, - (cos(u_roll/2)*cos(u_yaw/2)*sin(u_pitch/2))/2 - (cos(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2, - (cos(u_pitch/2)*cos(u_roll/2)*sin(u_yaw/2))/2 - (cos(u_yaw/2)*sin(u_pitch/2)*sin(u_roll/2))/2,   (cos(u_pitch/2)*cos(u_roll/2)*cos(u_yaw/2))/2 + (sin(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2;...
      0, 0, 0,   (cos(u_pitch/2)*cos(u_yaw/2)*sin(u_roll/2))/2 - (cos(u_roll/2)*sin(u_pitch/2)*sin(u_yaw/2))/2,   (cos(u_pitch/2)*cos(u_roll/2)*cos(u_yaw/2))/2 - (sin(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2,   (cos(u_pitch/2)*cos(u_roll/2)*sin(u_yaw/2))/2 - (cos(u_yaw/2)*sin(u_pitch/2)*sin(u_roll/2))/2;...
      0, 0, 0,   (cos(u_pitch/2)*cos(u_roll/2)*cos(u_yaw/2))/2 + (sin(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2, - (cos(u_pitch/2)*cos(u_yaw/2)*sin(u_roll/2))/2 - (cos(u_roll/2)*sin(u_pitch/2)*sin(u_yaw/2))/2, - (cos(u_roll/2)*cos(u_yaw/2)*sin(u_pitch/2))/2 - (cos(u_pitch/2)*sin(u_roll/2)*sin(u_yaw/2))/2];

end