function [A,B] = jacobian_pose_rblm_landmark_2d(x,l,z)

p_x = x(1);
p_y = x(2);
p_theta = x(3);

l_x = l(1);
l_y = l(2);

z_r = z(1);
z_theta = z(2);

A = ...
    [                                                                                                              ((2*cos(p_theta)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2 - (2*sin(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2)/(2*((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)^(1/2)),                                                                                                             ((2*cos(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (2*sin(p_theta)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2)/(2*((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)^(1/2));...
     -((sin(p_theta)/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)) + (cos(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)/(((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)*(cos(p_theta)^2 + sin(p_theta)^2)^2), ((cos(p_theta)/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)) - (sin(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)/(((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)*(cos(p_theta)^2 + sin(p_theta)^2)^2)];
 
B = ...
    [                                                                                                            -((2*cos(p_theta)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2 - (2*sin(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2)/(2*((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)^(1/2)),                                                                                                             -((2*cos(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (2*sin(p_theta)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)))/(cos(p_theta)^2 + sin(p_theta)^2)^2)/(2*((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)^(1/2)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0;...
    ((sin(p_theta)/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)) + (cos(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)/(((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)*(cos(p_theta)^2 + sin(p_theta)^2)^2), -((cos(p_theta)/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta)) - (sin(p_theta)*(l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta)))/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)/(((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)*(cos(p_theta)^2 + sin(p_theta)^2)^2), -(((l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2 + 1)*(l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2)/(((l_x*cos(p_theta) - p_x*cos(p_theta) + l_y*sin(p_theta) - p_y*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2 + (l_y*cos(p_theta) - p_y*cos(p_theta) - l_x*sin(p_theta) + p_x*sin(p_theta))^2/(cos(p_theta)^2 + sin(p_theta)^2)^2)*(cos(p_theta)^2 + sin(p_theta)^2)^2)];


end